name: Run test

on:
  push:
    branches: [ "tamnguyen/main" ]
  pull_request:
    branches: [ "tamnguyen/main" ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.4.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: pnpm install

      - run: pnpm run build

      - run: pnpm run test